import { AvailSettings } from '../contracts';
import { getNestedProp } from '../utils/common';

const moduleDefaults = {
    backgroundColor: true,
    border: true,
    borderRadius: true,
    boxShadow: true,
    color: true,
    display: true,
    flexDirection: true,
    flexWrap: true,
    flex: true,
    flexGrow: true,
    flexShrink: true,
    justifyContent: true,
    alignItems: true,
    alignContent: true,
    alignSelf: true,
    float: true,
    fontFamily: true,
    fontSize: true,
    fontStyle: true,
    fontWeight: true,
    overflow: true,
    overflowX: true,
    overflowY: true,
    position: true,
    width: true,
    height: true,
    minWidth: true,
    maxWidth: true,
    margin: true,
    padding: true,
    textAlign: true,
    textDecoration: true,
    textTransform: true,
    whitespace: true,
    transition: true,
    verticalAlign: true,
    visibility: true,
};

export default (config: Partial<AvailSettings> = {}): AvailSettings => {
    const configuredSettings = config || {};
    const _settings = {
        prefix: '',
        reboot: true,
        modules: moduleDefaults,
        breakpoints: {
            sm: '576px',
            md: '768px',
            lg: '992px',
            xl: '1200px',
        },
        grays: {
            '100': '#f8f9fa',
            '200': '#e9ecef',
            '300': '#dee2e6',
            '400': '#ced4da',
            '500': '#adb5bd',
            '600': '#6c757d',
            '700': '#495057',
            '800': '#343a40',
            '900': '#212529',
        },
        colors: {
            white: '#fff',
            black: '#000',
            blue: '#0d6efd',
            purple: '#6f42c1',
            pink: '#d63384',
            red: '#dc3545',
            orange: '#fd7e14',
            yellow: '#ffc107',
            green: '#28a745',
            teal: '#20c997',
            cyan: '#17a2b8',
            muted: '#6c757d',
        },
        variants: {
            primary: '',
            secondary: '',
            success: '',
            info: '',
            warning: '',
            danger: '',
            light: '',
            dark: '',
            white: '',
            black: '',
            transparent: 'transparent',
        },
        body: {},
        border: {},
        borderRadius: {},
        directions: {
            t: 'top',
            r: 'right',
            b: 'bottom',
            l: 'left',
            y: ['top', 'bottom'],
            x: ['left', 'right'],
        },
        fontFamilies: {
            mono: [
                'SFMono-Regular',
                'Menlo',
                'Monaco',
                'Consolas',
                '"Liberation Mono"',
                '"Courier New"',
                'monospace',
            ],
            sans: [
                '-apple-system',
                'BlinkMacSystemFont',
                '"Segoe UI"',
                'Roboto',
                '"Helvetica Neue"',
                'Arial',
                '"Noto Sans"',
                'sans-serif',
                '"Apple Color Emoji"',
                '"Segoe UI Emoji"',
                '"Segoe UI Symbol"',
                '"Noto Color Emoji"',
            ],
            serif: ['Georgia', 'Palatino', '"Times New Roman"', 'Times', 'serif'],
        },
        keywordSizes: {
            min: 'min-content',
            max: 'max-content',
            fit: 'fit-content',
            fill: 'fill-available',
        },
        negativeValuePrefix: 'n',
        negativeMarginPrefix: 'n',
        sizes: {
            '0': '0',
            '25': '25%',
            '50': '50%',
            '75': '75%',
            '100': '100%',
        },
        spacing: {
            0: '0',
            1: '.25rem',
            2: '.5rem',
            3: '1rem',
            4: '1.5rem',
            5: '3rem',
        },
    };
    _settings.body = {
        backgroundColor: getNestedProp(_settings, 'colors.white'),
        color: getNestedProp(_settings, 'grays.800'),
    };
    _settings.border = {
        width: {
            default: '1px',
            thick: '3px',
        },
        color: getNestedProp(_settings, 'grays.300'),
    };
    _settings.borderRadius = {
        default: '.25rem',
        small: '.125rem',
        large: '.5rem',
    };
    _settings.variants = {
        primary: getNestedProp(_settings, 'colors.blue'),
        secondary: getNestedProp(_settings, 'grays.600'),
        success: getNestedProp(_settings, 'colors.green'),
        info: getNestedProp(_settings, 'colors.cyan'),
        warning: getNestedProp(_settings, 'colors.yellow'),
        danger: getNestedProp(_settings, 'colors.red'),
        light: getNestedProp(_settings, 'grays.100'),
        dark: getNestedProp(_settings, 'grays.800'),
        white: getNestedProp(_settings, 'colors.white'),
        black: getNestedProp(_settings, 'colors.black'),
        transparent: 'transparent',
    };

    return { ..._settings, ...configuredSettings } as AvailSettings;
};
