/**
 * An object map of public property keys and their corresponding internal internal keys
 * (prefixed with `$`). The purpose of the internal keys is to denote semi-private properties
 * applied internally in core components and to differentiate from public properties that
 * are passed to a component instance.
 */
export const symbols = {
  background: '$background',
  border: '$border',
  borderX: '$borderX',
  borderY: '$borderY',
  borderTop: '$borderTop',
  borderRight: '$borderRight',
  borderBottom: '$borderBottom',
  borderLeft: '$borderLeft',
  color: '$color',
  display: '$display',
  boxSizing: '$boxSizing',
  flex: '$flex',
  direction: '$direction',
  wrap: '$wrap',
  align: '$align',
  justify: '$justify',
  font: '$font',
  fontFamily: '$fontFamily',
  fontSize: '$fontSize',
  fontStyle: '$fontStyle',
  fontWeight: '$fontWeight',
  lineHeight: '$lineHeight',
  autoRows: '$autoRows',
  autoCols: '$autoCols',
  autoFlow: '$autoFlow',
  columns: '$columns',
  gap: '$gap',
  gapX: '$gapX',
  gapY: '$gapY',
  rows: '$rows',
  column: '$column',
  columnStart: '$columnStart',
  columnEnd: '$columnEnd',
  row: '$row',
  rowStart: '$rowStart',
  rowEnd: '$rowEnd',
  height: '$height',
  maxHeight: '$maxHeight',
  m: '$margin',
  mx: '$marginX',
  my: '$marginY',
  mt: '$marginTop',
  mr: '$marginRight',
  mb: '$marginBottom',
  ml: '$marginLeft',
  margin: '$margin',
  marginX: '$marginX',
  marginY: '$marginY',
  marginTop: '$marginTop',
  marginRight: '$marginRight',
  marginBottom: '$marginBottom',
  marginLeft: '$marginLeft',
  overflow: '$overflow',
  p: '$padding',
  px: '$paddingX',
  py: '$paddingY',
  pt: '$paddingTop',
  pr: '$paddingRight',
  pb: '$paddingBottom',
  pl: '$paddingLeft',
  padding: '$padding',
  paddingX: '$paddingX',
  paddingY: '$paddingY',
  paddingTop: '$paddingTop',
  paddingRight: '$paddingRight',
  paddingBottom: '$paddingBottom',
  paddingLeft: '$paddingLeft',
  radius: '$radius',
  radiusTop: '$radiusTop',
  radiusRight: '$radiusRight',
  radiusBottom: '$radiusBottom',
  radiusLeft: '$radiusLeft',
  shadow: '$shadow',
  textAlign: '$textAlign',
  textOverflow: '$textOverflow',
  whiteSpace: '$whiteSpace',
  width: '$width',
  minWidth: '$minWidth',
  maxWidth: '$maxWidth',
  vAlign: '$vAlign',

  /**
   * Non-CSS Property constants
   */
  size: '$size',
  sizing: '$sizing',
  space: '$space',
  truncate: '$truncate',
}
